version: '2'
services:
        uploader:
                image: fono09/uploader
                volumes:
                        - /var/www/uploader:/var/www/uploader
                        - /etc/localtime:/etc/localtime:ro
                restart: always
