version: '2'
services:
        uploader:
                image: fono09/uploader:latest
                volumes:
                        - /var/www/uploader:/var/www/uploader
                restart: always
