version: '2'
services:
        uploader:
                build: .
                #image: fono09/uploader:latest
                volumes:
                        - /var/www/uploader:/var/www/uploader
                environment:
                        TZ: Asia/Tokyo
                restart: always
